#ifndef PACKETS_TS_CS_REQUEST_SECURITY_NO_CHANGE_H
#define PACKETS_TS_CS_REQUEST_SECURITY_NO_CHANGE_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_REQUEST_SECURITY_NO_CHANGE_DEF(_)

CREATE_PACKET(TS_CS_REQUEST_SECURITY_NO_CHANGE, 9008);

#endif // PACKETS_TS_CS_REQUEST_SECURITY_NO_CHANGE_H
