#ifndef PACKETS_TS_CS_TRANSMIT_ETHEREAL_DURABILITY_TO_EQUIPMENT_H
#define PACKETS_TS_CS_TRANSMIT_ETHEREAL_DURABILITY_TO_EQUIPMENT_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_TRANSMIT_ETHEREAL_DURABILITY_TO_EQUIPMENT_DEF(_) \
	_(simple)(float, rate) \
	_(simple)(int8_t, target)

CREATE_PACKET(TS_CS_TRANSMIT_ETHEREAL_DURABILITY_TO_EQUIPMENT, 264);

#endif // PACKETS_TS_CS_TRANSMIT_ETHEREAL_DURABILITY_TO_EQUIPMENT_H
