#ifndef PACKETS_TS_CS_REQUEST_CLEAR_SECURITY_NO_H
#define PACKETS_TS_CS_REQUEST_CLEAR_SECURITY_NO_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_REQUEST_CLEAR_SECURITY_NO_DEF(_)

CREATE_PACKET(TS_CS_REQUEST_CLEAR_SECURITY_NO, 9010);
#undef TS_CS_REQUEST_CLEAR_SECURITY_NO_DEF

#endif // PACKETS_TS_CS_REQUEST_CLEAR_SECURITY_NO_H
