#ifndef PACKETS_TS_CS_BATTLE_ARENA_LEAVE_H
#define PACKETS_TS_CS_BATTLE_ARENA_LEAVE_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_BATTLE_ARENA_LEAVE_DEF(_)

CREATE_PACKET(TS_CS_BATTLE_ARENA_LEAVE, 4704);

#endif // PACKETS_TS_CS_BATTLE_ARENA_LEAVE_H
