#pragma once

#include "Packet/PacketDeclaration.h"

#define TS_CS_BATTLE_ARENA_EXERCISE_START_DEF(_)

// Since EPIC_8_1
CREATE_PACKET(TS_CS_BATTLE_ARENA_EXERCISE_START, 4710);
#undef TS_CS_BATTLE_ARENA_EXERCISE_START_DEF

