#pragma once

#include "Packet/PacketDeclaration.h"

#define TS_CS_HUNTAHOLIC_BEGIN_HUNTING_DEF(_)

// Since EPIC_6_3
CREATE_PACKET(TS_CS_HUNTAHOLIC_BEGIN_HUNTING, 4011);
#undef TS_CS_HUNTAHOLIC_BEGIN_HUNTING_DEF

