#ifndef PACKETS_TS_CS_HUNTAHOLIC_LEAVE_LOBBY_H
#define PACKETS_TS_CS_HUNTAHOLIC_LEAVE_LOBBY_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_HUNTAHOLIC_LEAVE_LOBBY_DEF(_)

CREATE_PACKET(TS_CS_HUNTAHOLIC_LEAVE_LOBBY, 4008);
#undef TS_CS_HUNTAHOLIC_LEAVE_LOBBY_DEF

#endif // PACKETS_TS_CS_HUNTAHOLIC_LEAVE_LOBBY_H
