#pragma once

#include "Packet/PacketDeclaration.h"

#define TS_CS_INSTANCE_GAME_SCORE_REQUEST_DEF(_)

// Since EPIC_6_3
CREATE_PACKET(TS_CS_INSTANCE_GAME_SCORE_REQUEST, 4252);
#undef TS_CS_INSTANCE_GAME_SCORE_REQUEST_DEF

