#pragma once

#include "Packet/PacketDeclaration.h"

#define TS_CS_BATTLE_ARENA_ENTER_WHILE_COUNTDOWN_DEF(_)

// Since EPIC_8_1
CREATE_PACKET(TS_CS_BATTLE_ARENA_ENTER_WHILE_COUNTDOWN, 4707);
#undef TS_CS_BATTLE_ARENA_ENTER_WHILE_COUNTDOWN_DEF

