#ifndef PACKETS_TS_CS_BATTLE_ARENA_ABSENCE_CHECK_REQUEST_H
#define PACKETS_TS_CS_BATTLE_ARENA_ABSENCE_CHECK_REQUEST_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_BATTLE_ARENA_ABSENCE_CHECK_REQUEST_DEF(_) \
	_(simple)(uint32_t, hCheckTarget)

CREATE_PACKET(TS_CS_BATTLE_ARENA_ABSENCE_CHECK_REQUEST, 4717);

#endif // PACKETS_TS_CS_BATTLE_ARENA_ABSENCE_CHECK_REQUEST_H
