#ifndef PACKETS_TS_CS_BATTLE_ARENA_EXERCISE_START_H
#define PACKETS_TS_CS_BATTLE_ARENA_EXERCISE_START_H

#include "Packet/PacketDeclaration.h"

#define TS_CS_BATTLE_ARENA_EXERCISE_START_DEF(_)

CREATE_PACKET(TS_CS_BATTLE_ARENA_EXERCISE_START, 4710);

#endif // PACKETS_TS_CS_BATTLE_ARENA_EXERCISE_START_H
