#ifndef PACKETS_TS_SC_OPEN_PAID_STORAGE_H
#define PACKETS_TS_SC_OPEN_PAID_STORAGE_H

#include "Packet/PacketDeclaration.h"

#define TS_SC_OPEN_PAID_STORAGE_DEF(_)

CREATE_PACKET(TS_SC_OPEN_PAID_STORAGE, 10002);

#endif // PACKETS_TS_SC_OPEN_PAID_STORAGE_H
