#pragma once

#include "Packet/PacketDeclaration.h"

#define TS_SC_HUNTAHOLIC_MAX_POINT_ACHIEVED_DEF(_)

CREATE_PACKET(TS_SC_HUNTAHOLIC_MAX_POINT_ACHIEVED, 4010);
#undef TS_SC_HUNTAHOLIC_MAX_POINT_ACHIEVED_DEF

