#ifndef PACKETS_TS_SC_CHANGE_SECURITY_NO_H
#define PACKETS_TS_SC_CHANGE_SECURITY_NO_H

#include "Packet/PacketDeclaration.h"

#define TS_SC_CHANGE_SECURITY_NO_DEF(_)

CREATE_PACKET(TS_SC_CHANGE_SECURITY_NO, 9009);
#undef TS_SC_CHANGE_SECURITY_NO_DEF

#endif // PACKETS_TS_SC_CHANGE_SECURITY_NO_H
