#pragma once

#include "Packet/PacketDeclaration.h"

#define TS_SC_HUNTAHOLIC_BEGIN_COUNTDOWN_DEF(_)

// Since EPIC_6_3
CREATE_PACKET(TS_SC_HUNTAHOLIC_BEGIN_COUNTDOWN, 4012);
#undef TS_SC_HUNTAHOLIC_BEGIN_COUNTDOWN_DEF

