#pragma once

#include "Packet/PacketDeclaration.h"

#define TS_SC_SHOW_SOULSTONE_CRAFT_WINDOW_DEF(_)

CREATE_PACKET(TS_SC_SHOW_SOULSTONE_CRAFT_WINDOW, 259);
#undef TS_SC_SHOW_SOULSTONE_CRAFT_WINDOW_DEF

