#ifndef PACKETS_TS_CA_SERVER_LIST_H
#define PACKETS_TS_CA_SERVER_LIST_H

#include "Packet/PacketDeclaration.h"

#define TS_CA_SERVER_LIST_DEF(_)
CREATE_PACKET(TS_CA_SERVER_LIST, 10021);

#endif // PACKETS_TS_CA_SERVER_LIST_H
