#ifndef PACKETS_TS_CA_DISTRIBUTION_INFO_H
#define PACKETS_TS_CA_DISTRIBUTION_INFO_H

#include "PacketDeclaration.h"

#define TS_CA_DISTRIBUTION_INFO_DEF(simple_, array_, dynarray_, count_)

CREATE_PACKET(TS_CA_DISTRIBUTION_INFO, 10026);

#endif // PACKETS_TS_CA_DISTRIBUTION_INFO_H
